### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by CreeperLava** [jhass/crystal-gobject#19]
Hello ! I've been monitoring this project for a while, since I want to use gtk for a crystal application I plan on writing.

I saw you're still pushing commits every once in a while. Could you provide more details as to how usable this project is ? What works and what would be likely to break, if anything ?

Also, I'm quite curious as to how you generated these bindings. I searched a bit how bindings work in Crystal, and found the [bindgen](https://github.com/Papierkorb/bindgen) tool that can autogenerate bindings for a C library. Are you using something similar ? If I needed to add to or fix some bindings the ones you've already implemented, would bindgen be a good solution ?

Thank you !

**Comment by jhass** [comment]
The comment in the readme still applies. 

The entrypoint for the generator is at https://github.com/jhass/crystal-gobject/blob/master/src/generator/generator.cr
