### ISSUE TITLE
Destroy GTK events

### ISSUE THREAD

**Issue by webmastak** [jhass/crystal-gobject#25]
Hello.
Please tell me how to destroy GTK events.
I have an [application](https://github.com/webmastak/rss-feed-notifications/blob/master/src/rss-feed-notifications.cr) that shows notifications, but there is one problem.

When a notification is viewed, i.e. an GTK event and no longer fall into this cycle for the next notifi:
```
        while !Gtk.events_pending
          Gtk.main_iteration
          break if notification.on_closed { next true }
        end 
```
I am poorly versed in GTK and tried different options, and the best thing I think is to restart the application from myself with this code:
```
        if Gtk.events_pending
          File.write LOCK, e.pubDate 
          parent = Process.pid
          fork = Process.fork do
            Process.exec("#{PROGRAM_NAME}")
          end 
          Process.kill(Signal::KILL, parent)                      
        end
```
But the thought do this without restarting the application does not give me rest. :)

**Comment by jhass** [comment]
Why don't you let Gtk run the main loop (`Gtk.main_loop`) and use a glib timeout (`Glib.timeout(seconds) { callback }`) to poll your feed? As long as you return `true` from the callback it'll keep being called at the given interval. See https://developer.gnome.org/glib/stable/glib-The-Main-Event-Loop.html#g-timeout-add and https://github.com/jhass/crystal-gobject/blob/master/src/g_lib/g_lib.cr

**Comment by webmastak** [comment]
I'm just starting to study crystal.
You could not show on my [example](https://github.com/webmastak/rss-feed-notifications/blob/master/src/rss-feed-notifications.cr) how to implement it?
