### ISSUE TITLE
Question about Interfaces and includes

### ISSUE THREAD

**Issue by thiagoabreu** [jhass/crystal-gobject#28]
Hi.

I was reading the Gtk documentation, and found that some classes, i.e. `Gtk::ApplicationWindow`, implement some interfaces, i.e. `Gio::ActionMap`.

The thing is it doesn't look like it's been mapped to crystal by the generator.

I found putting this at my project make it work:

```crystal
module Gtk
  class Application
    include Gio::ActionMap
  end

  class ApplicationWindow
    include Gio::ActionMap
  end
end
```

Then I found the following code:

https://github.com/jhass/crystal-gobject/blob/3022dec48bf958779c2685b3ef7d92364166f054/src/g_i_repository/info/object_info.cr#L69-L72

And tried to change it to `include #{interface.namespace}::#{interface.name}`, but it seems to crash in some references.

Is there any plans to make it work at "generator-time" or do you think it's better to patch it by the consumer?

**Comment by jhass** [comment]
I definitely would love to have the generator do it, just didn't have the time yet myself to make it work. Any contributions welcome!

**Comment by jhass** [comment]
Okay, that was simpler than thought. Well at least it parses now.
