### ISSUE TITLE
Freebsd, sample hello world fails.

### ISSUE THREAD

**Issue by devosalain** [jhass/crystal-gobject#41]
crystal run samples/gtk_hello_world.cr
returns :
Syntax error in lib/gobject/g_i_repository/info/base_info.cr:115: unexpected token: :
 def dump(dumper, & : BaseInfo ->)
                                   I

**Comment by jhass** [comment]
Which Crystal version is that? :)

**Comment by devosalain** [comment]
Indeed, Crystal 0.28.0 (2020-02-07)

**Comment by jhass** [comment]
So yeah, current minium is 0.31, sorry :)

**Comment by devosalain** [comment]
I installed
Crystal 0.32.1 (2020-01-31) LLVM: 9.0.1 Default target: x86_64-portbld-freebsd12.1
Now it works. 
Just startup time of a gui application can sometimes take a few seconds.

**Comment by jhass** [comment]
You're probably seeing the compilation time, it generates a lot of code in the background :) especially on a cold cache that takes a while. If you run crystal build on a file, the resulting binary should boot a lot faster.

**Comment by devosalain** [comment]
For faster startup time now i compile with the options :
crystal build --verbose -s -p -t --mcpu ivybridge --release --no-debug --link-flags "-L$(pwd)"
