### ISSUE TITLE
About   fun _init_AnyClass = gtk_any_class_get_type

### ISSUE THREAD

**Issue by viachpaliy** [jhass/crystal-gobject#65]
I think, all this fun (for example, _init_AboutDialog) only return GType(a numerical value which represents the unique identifier of a registered type), not initialize any instance of class.Their uses in initialize methods make no sense.
It is only my opinion.

**Comment by jhass** [comment]
They are used to provide generic constructors using [`gobject_new_with_properties`](https://developer.gnome.org/gobject/2.64/gobject-The-Base-Object-Type.html#g-object-new-with-properties). See also https://developer.gnome.org/gobject/2.64/chapter-gobject.html#gobject-instantiation

Calling them also makes sure the GObject Type is actually initialized and registered into the type system, see [`g_registered_type_info_get_type_init`](https://developer.gnome.org/gi/stable/gi-GIRegisteredTypeInfo.html#g-registered-type-info-get-type-init).

**Comment by jhass** [comment]
I actually figured this out from crashes of not knowing you had to do this initially :)

**Comment by jhass** [comment]
Let's try through a popular provided constructor method: [`gtk_window_new'](https://gitlab.gnome.org/GNOME/gtk/-/blob/gtk-3-24/gtk/gtkwindow.c#L2326-2336). 

It calls `gobject_new` with [`GTK_TYPE_WINDOW`](https://gitlab.gnome.org/GNOME/gtk/-/blob/gtk-3-24/gtk/gtkwindow.h#L39) which is defined as:

```
#define GTK_TYPE_WINDOW			(gtk_window_get_type ())
```

which is [defined](https://gitlab.gnome.org/GNOME/gtk/-/blob/gtk-3-24/gtk/gtkwindow.c#L613) in this case by a call to [`G_DEFINE_TYPE_WITH_CODE`](https://gitlab.gnome.org/GNOME/glib/-/blob/glib-2-64/gobject/gtype.h#L1619)
```
G_DEFINE_TYPE_WITH_CODE (GtkWindow, gtk_window, ...
```
```
#define G_DEFINE_TYPE_WITH_CODE(TN, t_n, T_P, _C_)	    _G_DEFINE_TYPE_EXTENDED_BEGIN (TN, t_n, T_P, 0) {_C_;} _G_DEFINE_TYPE_EXTENDED_END()
```

[yada yada yada](https://gitlab.gnome.org/GNOME/glib/-/blob/glib-2-64/gobject/gtype.h#L1996-2010)

```
GType \
type_name##_get_type (void) \
{ \
  static volatile gsize g_define_type_id__volatile = 0;
  /* Prelude goes here */

/* Added for _G_DEFINE_TYPE_EXTENDED_WITH_PRELUDE */
#define _G_DEFINE_TYPE_EXTENDED_BEGIN_REGISTER(TypeName, type_name, TYPE_PARENT, flags) \
  if (g_once_init_enter (&g_define_type_id__volatile))  \
    { \
      GType g_define_type_id = type_name##_get_type_once (); \
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id); \
    }					\
  return g_define_type_id__volatile;	\
} /* closes type_name##_get_type() */ \
```

**Comment by jhass** [comment]
Alright, the above made me realize we can actually rely on that function to return the gtype, so I pushed a commit that makes use of that.

**Comment by viachpaliy** [comment]
Thank you for answer!
