### ISSUE TITLE
How can I import other GObject based libraries like Handy or Granite?

### ISSUE THREAD

**Issue by JeysonFlores** [jhass/crystal-gobject#84]
I saw a snippet in an old issue, something like
```Crystal
require "gobject"
require_gobject "Granite"
```
But this doesn't work, it throws a lot of error stuff. Does somebody have an idea?

**Comment by jhass** [comment]
Granite has an error in its GIR I think, it references `Granite.GraniteServicesSettingsSerializable` but only defines `ServicesSettingsSerializable` as far as I can tell.

**Comment by jhass** [comment]
Handy seems to load up fine for me, at least the minimal example of just loading it.

**Comment by jhass** [comment]
The last two commits should get Granite into the same state of the binding being syntactically valid.

**Comment by JeysonFlores** [comment]
Yeah, it works now! Thanks!
